name: Happo CI

on:
  pull_request:
    branches:
      - develop
    paths:
      - "src/**"

jobs:
  happo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      # - uses: ./.github/actions/setup
      - run: yarn run happo-ci
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
        env:
          HAPPO_IS_ASYNC: true
          BASE_BRANCH: \"origin/develop\"
          HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
          HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
          PREVIOUS_SHA: ${{ github.event.before }}
          CURRENT_SHA: ${{ github.event.after }}
          CHANGE_URL: ${{ github.event.head_commit.url }}
